<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


<script>


    // const pro = new Promise((resolve, reject) => {
    //
    //     setTimeout(() => {
    //
    //         if (Math.random() < 0.5) {
    //
    //             resolve(true);
    //
    //         } else {
    //
    //             resolve(false);
    //         }
    //
    //     }, 3000);
    //
    // });


    // function showLove(goddess) {
    //
    //     return new Promise((resolve, reject) => {
    //
    //         setTimeout(() => {
    //
    //             if (Math.random() < 0.5) {
    //
    //                 resolve(true);
    //
    //             } else {
    //
    //                 resolve(false);
    //             }
    //
    //         }, 3000);
    //     });
    // }
    //
    // showLove('goddess-1').then(data => {
    //
    //     console.log(data);
    // });


</script>

<script>


    /**
     * then-able 和 catch-able 函数是异步的，就算是立即执行，也会加入到事件队列中等待执行
     *
     *
     */

    // const pro = new Promise((resolve, reject) => {
    //
    //     console.log('a');
    //
    //     resolve(1);
    //
    //     console.log('b');
    // });
    //
    // pro.then(data => {
    //
    //     console.log(data);
    // });
    //
    // console.log('c');

    // a
    // b
    // c
    // 1


</script>

<script>


    const pro = new Promise((resolve, reject) => {

        console.log('a');

        resolve(1);

        setTimeout(() => {

            console.log('b');

        }, 0);

    });

    pro.then(data => {

        console.log(data);
    });

    console.log('c');

    // a
    // c
    // 1
    // b


</script>


</body>
</html>